// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.exchanges.NobitexCore;

public class NobitexApi extends NobitexCore
{

    public NobitexApi () {
        super();
    }

    public NobitexApi (Object options) {
        super(options);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV2TradesSymbol (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV2TradesSymbol", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV3OrderbookSymbol (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV3OrderbookSymbol", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetMarketStats (Object... optionalArgs)
    {
        return this.callAsync ("publicGetMarketStats", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetStatus (Object... optionalArgs)
    {
        return this.callAsync ("publicGetStatus", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetUsersProfile (Object... optionalArgs)
    {
        return this.callAsync ("privateGetUsersProfile", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetUsersTransactionsHistory (Object... optionalArgs)
    {
        return this.callAsync ("privateGetUsersTransactionsHistory", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetUsersMarketsFavorite (Object... optionalArgs)
    {
        return this.callAsync ("privateGetUsersMarketsFavorite", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostUsersWalletsList (Object... optionalArgs)
    {
        return this.callAsync ("privatePostUsersWalletsList", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostMarketOrdersAdd (Object... optionalArgs)
    {
        return this.callAsync ("privatePostMarketOrdersAdd", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostMarketOrdersCancel (Object... optionalArgs)
    {
        return this.callAsync ("privatePostMarketOrdersCancel", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostMarketOrdersList (Object... optionalArgs)
    {
        return this.callAsync ("privatePostMarketOrdersList", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostMarketOrdersUpdateStatus (Object... optionalArgs)
    {
        return this.callAsync ("privatePostMarketOrdersUpdateStatus", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostUsersAccountsAdd (Object... optionalArgs)
    {
        return this.callAsync ("privatePostUsersAccountsAdd", optionalArgs);
    }

}