// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.exchanges.WallexCore;

public class WallexApi extends WallexCore
{

    public WallexApi () {
        super();
    }

    public WallexApi (Object options) {
        super(options);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1Markets (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1Markets", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV2TradesSymbol (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV2TradesSymbol", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AccountBalances (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AccountBalances", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AccountOpenOrders (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AccountOpenOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1AccountOrders (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1AccountOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateDeleteV1AccountOrders (Object... optionalArgs)
    {
        return this.callAsync ("privateDeleteV1AccountOrders", optionalArgs);
    }

}