// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class nobitex : nobitex
{
    public nobitex (object args = null): base(args) {}

    public async Task<object> publicGetV2TradesSymbol (object parameters = null)
    {
        return await this.callAsync ("publicGetV2TradesSymbol",parameters);
    }

    public async Task<object> publicGetV3OrderbookSymbol (object parameters = null)
    {
        return await this.callAsync ("publicGetV3OrderbookSymbol",parameters);
    }

    public async Task<object> publicGetMarketStats (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketStats",parameters);
    }

    public async Task<object> publicGetStatus (object parameters = null)
    {
        return await this.callAsync ("publicGetStatus",parameters);
    }

    public async Task<object> privateGetUsersProfile (object parameters = null)
    {
        return await this.callAsync ("privateGetUsersProfile",parameters);
    }

    public async Task<object> privateGetUsersTransactionsHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetUsersTransactionsHistory",parameters);
    }

    public async Task<object> privateGetUsersMarketsFavorite (object parameters = null)
    {
        return await this.callAsync ("privateGetUsersMarketsFavorite",parameters);
    }

    public async Task<object> privatePostUsersWalletsList (object parameters = null)
    {
        return await this.callAsync ("privatePostUsersWalletsList",parameters);
    }

    public async Task<object> privatePostMarketOrdersAdd (object parameters = null)
    {
        return await this.callAsync ("privatePostMarketOrdersAdd",parameters);
    }

    public async Task<object> privatePostMarketOrdersCancel (object parameters = null)
    {
        return await this.callAsync ("privatePostMarketOrdersCancel",parameters);
    }

    public async Task<object> privatePostMarketOrdersList (object parameters = null)
    {
        return await this.callAsync ("privatePostMarketOrdersList",parameters);
    }

    public async Task<object> privatePostMarketOrdersUpdateStatus (object parameters = null)
    {
        return await this.callAsync ("privatePostMarketOrdersUpdateStatus",parameters);
    }

    public async Task<object> privatePostUsersAccountsAdd (object parameters = null)
    {
        return await this.callAsync ("privatePostUsersAccountsAdd",parameters);
    }

}