// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class wallex : wallex
{
    public wallex (object args = null): base(args) {}

    public async Task<object> publicGetV1Markets (object parameters = null)
    {
        return await this.callAsync ("publicGetV1Markets",parameters);
    }

    public async Task<object> publicGetV2TradesSymbol (object parameters = null)
    {
        return await this.callAsync ("publicGetV2TradesSymbol",parameters);
    }

    public async Task<object> privateGetV1AccountBalances (object parameters = null)
    {
        return await this.callAsync ("privateGetV1AccountBalances",parameters);
    }

    public async Task<object> privateGetV1AccountOpenOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetV1AccountOpenOrders",parameters);
    }

    public async Task<object> privatePostV1AccountOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostV1AccountOrders",parameters);
    }

    public async Task<object> privateDeleteV1AccountOrders (object parameters = null)
    {
        return await this.callAsync ("privateDeleteV1AccountOrders",parameters);
    }

}