// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *NobitexCore) PublicGetV2TradesSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetV2TradesSymbol", args...)
}

func (this *NobitexCore) PublicGetV3OrderbookSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetV3OrderbookSymbol", args...)
}

func (this *NobitexCore) PublicGetMarketStats(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetMarketStats", args...)
}

func (this *NobitexCore) PublicGetStatus(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetStatus", args...)
}

func (this *NobitexCore) PrivateGetUsersProfile(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetUsersProfile", args...)
}

func (this *NobitexCore) PrivateGetUsersTransactionsHistory(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetUsersTransactionsHistory", args...)
}

func (this *NobitexCore) PrivateGetUsersMarketsFavorite(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetUsersMarketsFavorite", args...)
}

func (this *NobitexCore) PrivatePostUsersWalletsList(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostUsersWalletsList", args...)
}

func (this *NobitexCore) PrivatePostMarketOrdersAdd(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarketOrdersAdd", args...)
}

func (this *NobitexCore) PrivatePostMarketOrdersCancel(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarketOrdersCancel", args...)
}

func (this *NobitexCore) PrivatePostMarketOrdersList(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarketOrdersList", args...)
}

func (this *NobitexCore) PrivatePostMarketOrdersUpdateStatus(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostMarketOrdersUpdateStatus", args...)
}

func (this *NobitexCore) PrivatePostUsersAccountsAdd(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostUsersAccountsAdd", args...)
}
