// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *WallexCore) PublicGetV1Markets(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetV1Markets", args...)
}

func (this *WallexCore) PublicGetV2TradesSymbol(args ...any) <-chan any {
	return this.callEndpointAsync("publicGetV2TradesSymbol", args...)
}

func (this *WallexCore) PrivateGetV1AccountBalances(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetV1AccountBalances", args...)
}

func (this *WallexCore) PrivateGetV1AccountOpenOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateGetV1AccountOpenOrders", args...)
}

func (this *WallexCore) PrivatePostV1AccountOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privatePostV1AccountOrders", args...)
}

func (this *WallexCore) PrivateDeleteV1AccountOrders(args ...any) <-chan any {
	return this.callEndpointAsync("privateDeleteV1AccountOrders", args...)
}
