# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.nobitex import ImplicitAPI
from ccxt.base.types import Any, Balances, Int, Market, Order, OrderBook, Str, Ticker, Tickers, Trade, MarketInterface
from typing import List
from ccxt.base.errors import OrderNotFound
from ccxt.base.errors import NotSupported


class nobitex(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(nobitex, self).describe(), {
            'id': 'nobitex',
            'name': 'Nobitex',
            'countries': ['IR'],
            'rateLimit': 100,
            'certified': False,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'cancelOrder': True,
                'createOrder': True,
                'fetchBalance': True,
                'fetchClosedOrders': True,
                'fetchMarkets': True,
                'fetchMyTrades': True,
                'fetchOHLCV': False,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchOrders': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTrades': True,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
            },
            'urls': {
                'logo': 'https://nobitex.ir/assets/images/logo.svg',
                'api': {
                    'public': 'https://apiv2.nobitex.ir',
                    'private': 'https://apiv2.nobitex.ir',
                },
                'www': 'https://nobitex.ir',
                'doc': ['https://apidocs.nobitex.ir'],
            },
            'api': {
                'public': {
                    'get': [
                        'v2/trades/{symbol}',
                        'v3/orderbook/{symbol}',
                        'market/stats',
                        'status',
                    ],
                },
                'private': {
                    'get': [
                        'users/profile',
                        'users/transactions-history',
                        'users/markets/favorite',
                    ],
                    'post': [
                        'users/wallets/list',
                        'market/orders/add',
                        'market/orders/cancel',
                        'market/orders/list',
                        'market/orders/update-status',
                        'users/accounts-add',
                    ],
                },
            },
            'requiredCredentials': {
                'apiKey': True,
                'secret': False,
            },
            'options': {
                'defaultType': 'spot',
            },
        })

    def sign(self, path: str, api: str = 'public', method: str = 'GET', params: dict = {}, headers: dict = {}, body: Str = None) -> Any:
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            if method == 'GET':
                url += '?' + self.urlencode(query)
        if headers == 0:
            headers = {}
        headers['User-Agent'] = 'Mozilla/5.0(Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        if api == 'private':
            self.check_required_credentials()
            headers['Authorization'] = 'Token ' + self.apiKey
            if method == 'POST':
                headers['Content-Type'] = 'application/x-www-form-urlencoded'
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    async def fetch_markets(self, params={}) -> List[MarketInterface]:
        response = await self.request('market/stats', 'public', 'GET', params)
        stats = self.safe_dict(response, 'stats', {})
        keys = list(stats.keys())
        markets = []
        for i in range(0, len(keys)):
            id = keys[i]
            parts = id.split('-')
            if len(parts) != 2:
                continue
            baseId = parts[0]
            quoteId = parts[1]
            base = self.safe_currency_code(baseId)
            quote = self.safe_currency_code(quoteId)
            markets.append({
                'id': id,
                'symbol': base + '/' + quote,
                'base': base,
                'quote': quote,
                'settle': None,
                'baseId': baseId,
                'quoteId': quoteId,
                'settleId': None,
                'type': 'spot',
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'active': True,
                'contract': False,
                'linear': None,
                'inverse': None,
                'subType': None,
                'taker': None,
                'maker': None,
                'contractSize': None,
                'expiry': None,
                'expiryDatetime': None,
                'strike': None,
                'optionType': None,
                'precision': {
                    'amount': self.parse_number('0.000001'),
                    'price': self.parse_number('1'),
                    'cost': None,
                },
                'limits': {
                    'leverage': {'min': None, 'max': None},
                    'amount': {'min': None, 'max': None},
                    'price': {'min': None, 'max': None},
                    'cost': {'min': None, 'max': None},
                },
                'marginModes': {
                    'isolated': False,
                    'cross': False,
                },
                'created': None,
                'info': stats[id],
            })
        return markets

    def parse_ticker(self, ticker: dict, market: MarketInterface | None = None) -> Ticker:
        timestamp = self.milliseconds()
        symbol = self.safe_string(market, 'symbol')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_number(ticker, 'dayHigh'),
            'low': self.safe_number(ticker, 'dayLow'),
            'bid': self.safe_number(ticker, 'bestBuy'),
            'bidVolume': None,
            'ask': self.safe_number(ticker, 'bestSell'),
            'askVolume': None,
            'vwap': None,
            'open': self.safe_number(ticker, 'dayOpen'),
            'close': self.safe_number(ticker, 'latest'),
            'last': self.safe_number(ticker, 'latest'),
            'previousClose': None,
            'change': None,
            'percentage': self.safe_number(ticker, 'dayChange'),
            'average': None,
            'baseVolume': self.safe_number(ticker, 'volumeSrc'),
            'quoteVolume': self.safe_number(ticker, 'volumeDst'),
            'info': ticker,
        }, market)

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'srcCurrency': market['baseId'],
            'dstCurrency': market['quoteId'],
        }
        response = await self.request('market/stats', 'public', 'GET', self.extend(request, params))
        stats = self.safe_dict(response, 'stats', {})
        tickerKey = market['baseId'] + '-' + market['quoteId']
        ticker = self.safe_dict(stats, tickerKey, {})
        return self.parse_ticker(ticker, market)

    async def fetch_tickers(self, symbols: List[Str] | None = None, params={}) -> Tickers:
        await self.load_markets()
        result = {}
        for(symbol in self.markets) {
            market = self.markets[symbol]
            info = self.safe_dict(market, 'info')
            if info is not None:
                result[symbol] = self.parse_ticker(info, market)
        return result

    async def fetch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
        await self.load_markets()
        market = self.market(symbol)
        requestSymbol = market['baseId'].upper() + market['quoteId'].upper()
        response = await self.request('v3/orderbook/' + requestSymbol, 'public', 'GET', params)
        return self.parse_order_book(response, market['symbol'])

    async def fetch_ohlcv(self, symbol: str, timeframe: str = '1d', since: Int = None, limit: Int = None, params={}) -> List[list]:
        raise NotSupported(self.id + ' fetchOHLCV() is not supported by the Nobitex API.')

    async def fetch_trades(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        await self.load_markets()
        market = self.market(symbol)
        requestSymbol = market['baseId'].upper() + market['quoteId'].upper()
        response = await self.request('v2/trades/' + requestSymbol, 'public', 'GET', params)
        return self.parse_trades(response, market, since, limit)

    async def fetch_balance(self, params={}) -> Balances:
        await self.load_markets()
        response = await self.request('users/wallets/list', 'private', 'POST', params)
        wallets = self.safe_list(response, 'wallets', [])
        result = {'info': response}
        for i in range(0, len(wallets)):
            wallet = wallets[i]
            currencyId = self.safe_string(wallet, 'currency')
            code = self.safe_currency_code(currencyId)
            # استفاده از safeNumber به جای safeString و تفریق استاندارد
            total = self.safe_number(wallet, 'balance')
            free = self.safe_number(wallet, 'activeBalance')
            used = None
            if total is not None and free is not None:
                used = total - free
            result[code] = {
                'free': free,
                'used': used,
                'total': total,
            }
        return self.safe_balance(result)

    def parse_order_status(self, status: Str) -> Str:
        statuses = {
            'open': 'open',
            'active': 'open',
            'done': 'closed',
            'filled': 'closed',
            'canceled': 'canceled',
            'cancelled': 'canceled',
        }
        return self.safe_string(statuses, status, status)

    def parse_order(self, order: dict, market: MarketInterface | None = None) -> Order:
        id = self.safe_string(order, 'id')
        timestamp = self.safe_timestamp(order, 'createdAt')
        symbol = self.safe_string(market, 'symbol')
        return self.safe_order({
            'id': id,
            'clientOrderId': None,
            'info': order,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': None,
            'status': self.parse_order_status(self.safe_string(order, 'status')),
            'symbol': symbol,
            'type': self.safe_string(order, 'type'),
            'timeInForce': None,
            'side': self.safe_string_lower(order, 'type'),
            'price': self.safe_number(order, 'price'),
            'amount': self.safe_number(order, 'amount'),
            'filled': self.safe_number(order, 'filledAmount'),
            'remaining': None,
            'cost': None,
            'average': None,
            'trades': [],
            'fee': None,
        }, market)

    async def create_order(self, symbol: str, type: str, side: str, amount: float, price: float | None = None, params={}) -> Order:
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'type': type,
            'srcCurrency': market['baseId'],
            'dstCurrency': market['quoteId'],
            'amount': amount,
            'side': side,
        }
        if price is not None:
            request['price'] = price
        response = await self.request('market/orders/add', 'private', 'POST', self.extend(request, params))
        order = self.safe_dict(response, 'order', response)
        return self.parse_order(order, market)

    async def cancel_order(self, id: str, symbol: Str = None, params={}) -> Order:
        await self.load_markets()
        request = {
            'order': id,
            'status': 'canceled',
        }
        response = await self.request('market/orders/update-status', 'private', 'POST', self.extend(request, params))
        return response

    async def fetch_order(self, id: str, symbol: Str = None, params={}) -> Order:
        await self.load_markets()
        orders = await self.fetch_orders(symbol, None, None, params)
        for i in range(0, len(orders)):
            if orders[i]['id'] == str(id):
                return orders[i]
        raise OrderNotFound('Order not found: ' + str(id))

    async def fetch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        await self.load_markets()
        market = None
        request = {}
        if symbol is not None:
            market = self.market(symbol)
            request['srcCurrency'] = market['baseId']
            request['dstCurrency'] = market['quoteId']
        response = await self.request('market/orders/list', 'private', 'POST', self.extend(request, params))
        orders = self.safe_list(response, 'orders', [])
        return self.parse_orders(orders, market, since, limit)

    async def fetch_open_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        request = {'status': 'open'}
        return self.fetch_orders(symbol, since, limit, self.extend(request, params))

    async def fetch_closed_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        request = {'status': 'done'}
        return self.fetch_orders(symbol, since, limit, self.extend(request, params))

    async def fetch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        request = {'status': 'done'}
        orders = await self.fetch_orders(symbol, since, limit, self.extend(request, params))
        return orders
