# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.wallex import ImplicitAPI
from ccxt.base.types import Any, Balances, Int, Market, Order, Str, Ticker, Tickers, MarketInterface
from typing import List


class wallex(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(wallex, self).describe(), {
            'id': 'wallex',
            'name': 'Wallex',
            'countries': ['IR'],
            'version': 'v1',
            'rateLimit': 200,
            'certified': False,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': None,
                'cancelOrder': True,
                'createOrder': True,
                'fetchBalance': True,
                'fetchMarkets': True,
                'fetchMyTrades': False,
                'fetchOHLCV': False,  # Wallex supports it via udf, but we disable for now to keep it simple
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchOrders': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTrades': True,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
            },
            'urls': {
                'logo': 'https://wallex.ir/assets/images/logo.svg',
                'api': {
                    'public': 'https://api.wallex.ir',
                    'private': 'https://api.wallex.ir',
                },
                'www': 'https://wallex.ir',
                'doc': ['https://developers.wallex.ir/'],
            },
            'api': {
                'public': {
                    'get': [
                        'v1/markets',
                        'v2/trades/{symbol}',  # Hypothetical endpoint for trades
                    ],
                },
                'private': {
                    'get': [
                        'v1/account/balances',
                        'v1/account/openOrders',
                    ],
                    'post': [
                        'v1/account/orders',
                    ],
                    'delete': [
                        'v1/account/orders',
                    ],
                },
            },
            'requiredCredentials': {
                'apiKey': True,
                'secret': False,
            },
            'options': {
                'defaultType': 'spot',
            },
        })

    def sign(self, path: str, api: str = 'public', method: str = 'GET', params: dict = {}, headers: dict = {}, body: Str = None) -> Any:
        url = self.urls['api'][api] + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if query:
            if method == 'GET':
                url += '?' + self.urlencode(query)
        if headers == 0:
            headers = {}
        headers['User-Agent'] = 'Mozilla/5.0(Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        if api == 'private':
            self.check_required_credentials()
            headers['x-api-key'] = self.apiKey
            if method == 'POST' or method == 'DELETE':
                headers['Content-Type'] = 'application/json'
                body = self.json(query)
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    async def fetch_markets(self, params={}) -> List[MarketInterface]:
        response = await self.request('v1/markets', 'public', 'GET', params)
        result = self.safe_dict(response, 'result', {})
        symbols = self.safe_dict(result, 'symbols', {})
        keys = list(symbols.keys())
        markets = []
        for i in range(0, len(keys)):
            id = keys[i]
            market = self.safe_dict(symbols, id, {})
            base = self.safe_string(market, 'baseAsset')
            quote = self.safe_string(market, 'quoteAsset')
            if (base is None) or (quote is None):
                continue
            markets.append({
                'id': id,
                'symbol': base + '/' + quote,
                'base': base,
                'quote': quote,
                'baseId': base,
                'quoteId': quote,
                'type': 'spot',
                'spot': True,
                'active': True,
                'precision': {
                    'amount': self.safe_integer(market, 'stepSize'),
                    'price': self.safe_integer(market, 'tickSize'),
                },
                'limits': {
                    'amount': {'min': self.safe_number(market, 'minQty'), 'max': None},
                    'price': {'min': None, 'max': None},
                    'cost': {'min': None, 'max': None},
                },
                'info': market,
            })
        return markets

    def parse_ticker(self, ticker: dict, market: MarketInterface | None = None) -> Ticker:
        timestamp = self.milliseconds()
        symbol = self.safe_string(market, 'symbol')
        stats = self.safe_dict(ticker, 'stats', {})
        last = self.safe_number(stats, 'lastPrice')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_number(stats, '24h_highPrice'),
            'low': self.safe_number(stats, '24h_lowPrice'),
            'bid': self.safe_number(stats, 'bidPrice'),
            'ask': self.safe_number(stats, 'askPrice'),
            'last': last,
            'close': last,
            'baseVolume': self.safe_number(stats, '24h_volume'),
            'quoteVolume': self.safe_number(stats, '24h_quoteVolume'),
            'info': ticker,
        }, market)

    async def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        await self.load_markets()
        market = self.market(symbol)
        response = await self.request('v1/markets', 'public', 'GET', params)
        result = self.safe_dict(response, 'result', {})
        symbols = self.safe_dict(result, 'symbols', {})
        data = self.safe_dict(symbols, market['id'], {})
        return self.parse_ticker(data, market)

    async def fetch_tickers(self, symbols: List[Str] | None = None, params={}) -> Tickers:
        await self.load_markets()
        response = await self.request('v1/markets', 'public', 'GET', params)
        result = self.safe_dict(response, 'result', {})
        symbolsData = self.safe_dict(result, 'symbols', {})
        keys = list(symbolsData.keys())
        tickers = {}
        for i in range(0, len(keys)):
            id = keys[i]
            market = self.safe_value(self.markets_by_id, id)
            if market is not None:
                ticker = self.parse_ticker(symbolsData[id], market)
                tickers[market['symbol']] = ticker
        return tickers

    async def fetch_balance(self, params={}) -> Balances:
        await self.load_markets()
        response = await self.request('v1/account/balances', 'private', 'GET', params)
        result = self.safe_dict(response, 'result', {})
        balances = {'info': response}
        values = list(result.values())
        for i in range(0, len(values)):
            item = values[i]
            if (item == None) or (not isinstance(item, dict)):
                continue
            balance = item
            code = self.safe_string(balance, 'asset')
            if code is None:
                continue
            total = self.safe_number(balance, 'balance')
            free = self.safe_number(balance, 'available')
            used = self.safe_number(balance, 'freeze')
            balances[code] = {'free': free, 'used': used, 'total': total}
        return self.safe_balance(balances)

    async def create_order(self, symbol: str, type: str, side: str, amount: float, price: float | None = None, params={}) -> Order:
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'symbol': market['id'],
            'side': side,
            'type': type,  # limit or market
            'quantity': self.amount_to_precision(symbol, amount),
        }
        if price is not None:
            request['price'] = self.price_to_precision(symbol, price)
        response = await self.request('v1/account/orders', 'private', 'POST', self.extend(request, params))
        orderData = self.safe_dict(response, 'result', response)
        return self.parse_order(orderData, market)

    async def cancel_order(self, id: str, symbol: Str = None, params={}) -> Order:
        request = {'client_id': id}
        response = await self.request('v1/account/orders', 'private', 'DELETE', self.extend(request, params))
        return response

    def parse_order(self, order: dict, market: MarketInterface | None = None) -> Order:
        id = self.safe_string(order, 'clientOrderId')
        timestamp = self.safe_integer(order, 'transactTime')
        symbol = self.safe_string(market, 'symbol')
        return self.safe_order({
            'id': id,
            'clientOrderId': id,
            'info': order,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'status': self.safe_string_lower(order, 'status'),
            'symbol': symbol,
            'type': self.safe_string_lower(order, 'type'),
            'side': self.safe_string_lower(order, 'side'),
            'price': self.safe_number(order, 'price'),
            'amount': self.safe_number(order, 'origQty'),
            'filled': self.safe_number(order, 'executedQty'),
            'remaining': None,
            'cost': None,
            'fee': None,
            'trades': None,
        }, market)

    async def fetch_open_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        await self.load_markets()
        market = None
        if symbol is not None:
            market = self.market(symbol)
        response = await self.request('v1/account/openOrders', 'private', 'GET', params)
        result = self.safe_dict(response, 'result', {})
        orders = self.safe_list(result, 'orders', [])
        return self.parse_orders(orders, market, since, limit)
