<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class nobitex extends \ccxt\async\nobitex {
    public function public_get_v2_trades_symbol($params = array()) {
        return $this->request('v2/trades/{symbol}', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_v3_orderbook_symbol($params = array()) {
        return $this->request('v3/orderbook/{symbol}', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_market_stats($params = array()) {
        return $this->request('market/stats', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_status($params = array()) {
        return $this->request('status', 'public', 'GET', $params, null, null, array());
    }
    public function private_get_users_profile($params = array()) {
        return $this->request('users/profile', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_users_transactions_history($params = array()) {
        return $this->request('users/transactions-history', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_users_markets_favorite($params = array()) {
        return $this->request('users/markets/favorite', 'private', 'GET', $params, null, null, array());
    }
    public function private_post_users_wallets_list($params = array()) {
        return $this->request('users/wallets/list', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_market_orders_add($params = array()) {
        return $this->request('market/orders/add', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_market_orders_cancel($params = array()) {
        return $this->request('market/orders/cancel', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_market_orders_list($params = array()) {
        return $this->request('market/orders/list', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_market_orders_update_status($params = array()) {
        return $this->request('market/orders/update-status', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_users_accounts_add($params = array()) {
        return $this->request('users/accounts-add', 'private', 'POST', $params, null, null, array());
    }
    public function publicGetV2TradesSymbol($params = array()) {
        return $this->request('v2/trades/{symbol}', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetV3OrderbookSymbol($params = array()) {
        return $this->request('v3/orderbook/{symbol}', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetMarketStats($params = array()) {
        return $this->request('market/stats', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetStatus($params = array()) {
        return $this->request('status', 'public', 'GET', $params, null, null, array());
    }
    public function privateGetUsersProfile($params = array()) {
        return $this->request('users/profile', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUsersTransactionsHistory($params = array()) {
        return $this->request('users/transactions-history', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUsersMarketsFavorite($params = array()) {
        return $this->request('users/markets/favorite', 'private', 'GET', $params, null, null, array());
    }
    public function privatePostUsersWalletsList($params = array()) {
        return $this->request('users/wallets/list', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostMarketOrdersAdd($params = array()) {
        return $this->request('market/orders/add', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostMarketOrdersCancel($params = array()) {
        return $this->request('market/orders/cancel', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostMarketOrdersList($params = array()) {
        return $this->request('market/orders/list', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostMarketOrdersUpdateStatus($params = array()) {
        return $this->request('market/orders/update-status', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostUsersAccountsAdd($params = array()) {
        return $this->request('users/accounts-add', 'private', 'POST', $params, null, null, array());
    }
}
