<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class wallex extends \ccxt\async\wallex {
    public function public_get_v1_markets($params = array()) {
        return $this->request('v1/markets', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_v2_trades_symbol($params = array()) {
        return $this->request('v2/trades/{symbol}', 'public', 'GET', $params, null, null, array());
    }
    public function private_get_v1_account_balances($params = array()) {
        return $this->request('v1/account/balances', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_v1_account_openorders($params = array()) {
        return $this->request('v1/account/openOrders', 'private', 'GET', $params, null, null, array());
    }
    public function private_post_v1_account_orders($params = array()) {
        return $this->request('v1/account/orders', 'private', 'POST', $params, null, null, array());
    }
    public function private_delete_v1_account_orders($params = array()) {
        return $this->request('v1/account/orders', 'private', 'DELETE', $params, null, null, array());
    }
    public function publicGetV1Markets($params = array()) {
        return $this->request('v1/markets', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetV2TradesSymbol($params = array()) {
        return $this->request('v2/trades/{symbol}', 'public', 'GET', $params, null, null, array());
    }
    public function privateGetV1AccountBalances($params = array()) {
        return $this->request('v1/account/balances', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetV1AccountOpenOrders($params = array()) {
        return $this->request('v1/account/openOrders', 'private', 'GET', $params, null, null, array());
    }
    public function privatePostV1AccountOrders($params = array()) {
        return $this->request('v1/account/orders', 'private', 'POST', $params, null, null, array());
    }
    public function privateDeleteV1AccountOrders($params = array()) {
        return $this->request('v1/account/orders', 'private', 'DELETE', $params, null, null, array());
    }
}
