<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\nobitex as Exchange;

class nobitex extends Exchange {
    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'nobitex',
            'name' => 'Nobitex',
            'countries' => array( 'IR' ),
            'rateLimit' => 100,
            'certified' => false,
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'cancelOrder' => true,
                'createOrder' => true,
                'fetchBalance' => true,
                'fetchClosedOrders' => true,
                'fetchMarkets' => true,
                'fetchMyTrades' => true,
                'fetchOHLCV' => false,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrderBook' => true,
                'fetchOrders' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTrades' => true,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
            ),
            'urls' => array(
                'logo' => 'https://nobitex.ir/assets/images/logo.svg',
                'api' => array(
                    'public' => 'https://apiv2.nobitex.ir',
                    'private' => 'https://apiv2.nobitex.ir',
                ),
                'www' => 'https://nobitex.ir',
                'doc' => array( 'https://apidocs.nobitex.ir' ),
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v2/trades/{$symbol}',
                        'v3/orderbook/{$symbol}',
                        'market/stats',
                        'status',
                    ),
                ),
                'private' => array(
                    'get' => array(
                        'users/profile',
                        'users/transactions-history',
                        'users/markets/favorite',
                    ),
                    'post' => array(
                        'users/wallets/list',
                        'market/orders/add',
                        'market/orders/cancel',
                        'market/orders/list',
                        'market/orders/update-status',
                        'users/accounts-add',
                    ),
                ),
            ),
            'requiredCredentials' => array(
                'apiKey' => true,
                'secret' => false,
            ),
            'options' => array(
                'defaultType' => 'spot',
            ),
        ));
    }
    override sign (path => string, api => string = 'public', method => string = 'GET', params => Dict = array(), headers => Dict = array(), body => Str = null) => any {
        $url = $this->urls['api'][api] . '/' . $this->implode_params(path, params);
        $query = $this->omit(params, $this->extract_params(path));
        if ($query) {
            if (method === 'GET') {
                $url .= '?' . $this->urlencode($query);
            }
        }
        if (headers === 0) {
            headers = array();
        }
        headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36';
        if (api === 'private') {
            $this->check_required_credentials();
            headers['Authorization'] = 'Token ' . $this->apiKey;
            if (method === 'POST') {
                headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }
        return array( 'url' => $url, 'method' => method, 'body' => body, 'headers' => headers );
    }
    override async fetchMarkets (params = array()) => Promise<MarketInterfacearray()> {
        $response = $this->request('market/stats', 'public', 'GET', params);
        $stats = $this->safe_dict($response, 'stats', array());
        $keys = is_array($stats) ? array_keys($stats) : array();
        $markets = array();
        for ($i = 0; $i < count($keys); $i++) {
            $id = $keys[$i];
            $parts = explode('-', $id);
            if (strlen($parts) !== 2) {
                continue;
            }
            $baseId = $parts[0];
            $quoteId = $parts[1];
            $base = $this->safe_currency_code($baseId);
            $quote = $this->safe_currency_code($quoteId);
            $markets[] = array(
                'id' => $id,
                'symbol' => $base . '/' . $quote,
                'base' => $base,
                'quote' => $quote,
                'settle' => null,
                'baseId' => $baseId,
                'quoteId' => $quoteId,
                'settleId' => null,
                'type' => 'spot',
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'active' => true,
                'contract' => false,
                'linear' => null,
                'inverse' => null,
                'subType' => null,
                'taker' => null,
                'maker' => null,
                'contractSize' => null,
                'expiry' => null,
                'expiryDatetime' => null,
                'strike' => null,
                'optionType' => null,
                'precision' => array(
                    'amount' => $this->parse_number('0.000001'),
                    'price' => $this->parse_number('1'),
                    'cost' => null,
                ),
                'limits' => array(
                    'leverage' => array( 'min' => null, 'max' => null ),
                    'amount' => array( 'min' => null, 'max' => null ),
                    'price' => array( 'min' => null, 'max' => null ),
                    'cost' => array( 'min' => null, 'max' => null ),
                ),
                'marginModes' => array(
                    'isolated' => false,
                    'cross' => false,
                ),
                'created' => null,
                'info' => $stats[$id],
            );
        }
        return $markets;
    }
    override parseTicker ($ticker => Dict, $market => MarketInterface | null = null) => Ticker {
        $timestamp = $this->milliseconds();
        $symbol = $this->safe_string($market, 'symbol');
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'high' => $this->safe_number($ticker, 'dayHigh'),
            'low' => $this->safe_number($ticker, 'dayLow'),
            'bid' => $this->safe_number($ticker, 'bestBuy'),
            'bidVolume' => null,
            'ask' => $this->safe_number($ticker, 'bestSell'),
            'askVolume' => null,
            'vwap' => null,
            'open' => $this->safe_number($ticker, 'dayOpen'),
            'close' => $this->safe_number($ticker, 'latest'),
            'last' => $this->safe_number($ticker, 'latest'),
            'previousClose' => null,
            'change' => null,
            'percentage' => $this->safe_number($ticker, 'dayChange'),
            'average' => null,
            'baseVolume' => $this->safe_number($ticker, 'volumeSrc'),
            'quoteVolume' => $this->safe_number($ticker, 'volumeDst'),
            'info' => $ticker,
        ), $market);
    }
    override async fetchTicker ($symbol => string, params = array()) => Promise<Ticker> {
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'srcCurrency' => $market['baseId'],
            'dstCurrency' => $market['quoteId'],
        );
        $response = $this->request('market/stats', 'public', 'GET', $this->extend($request, params));
        $stats = $this->safe_dict($response, 'stats', array());
        $tickerKey = $market['baseId'] . '-' . $market['quoteId'];
        $ticker = $this->safe_dict($stats, $tickerKey, array());
        return $this->parse_ticker($ticker, $market);
    }
    override async fetchTickers (symbols => Strarray() | null = null, params = array()) => Promise<Tickers> {
        $this->load_markets();
        $result = array();
        for (is_array($this->markets) && array_key_exists($symbol, $this->markets)) {
            $market = $this->markets[$symbol];
            $info = $this->safe_dict($market, 'info');
            if ($info !== null) {
                $result[$symbol] = $this->parse_ticker($info, $market);
            }
        }
        return $result;
    }
    override async fetchOrderBook ($symbol => string, limit => Int = null, params = array()) => Promise<OrderBook> {
        $this->load_markets();
        $market = $this->market($symbol);
        $requestSymbol = strtoupper($market['baseId']) . strtoupper($market['quoteId']);
        $response = $this->request('v3/orderbook/' . $requestSymbol, 'public', 'GET', params);
        return $this->parse_order_book($response, $market['symbol']);
    }
    override async fetchOHLCV ($symbol => string, timeframe => string = '1d', since => Int = null, limit => Int = null, params = array()) => Promise<OHLCVarray()> {
        throw new NotSupported($this->id . ' fetchOHLCV() is not supported by the Nobitex API.');
    }
    override async fetchTrades ($symbol => string, since => Int = null, limit => Int = null, params = array()) => Promise<Tradearray()> {
        $this->load_markets();
        $market = $this->market($symbol);
        $requestSymbol = strtoupper($market['baseId']) . strtoupper($market['quoteId']);
        $response = $this->request('v2/trades/' . $requestSymbol, 'public', 'GET', params);
        return $this->parse_trades($response, $market, since, limit);
    }
    override async fetchBalance (params = array()) => Promise<Balances> {
        $this->load_markets();
        $response = $this->request('users/wallets/list', 'private', 'POST', params);
        $wallets = $this->safe_list($response, 'wallets', array());
        $result = array( 'info' => $response );
        for ($i = 0; $i < count($wallets); $i++) {
            $wallet = $wallets[$i];
            $currencyId = $this->safe_string($wallet, 'currency');
            $code = $this->safe_currency_code($currencyId);
            // استفاده از safeNumber به جای safeString و تفریق استاندارد
            $total = $this->safe_number($wallet, 'balance');
            $free = $this->safe_number($wallet, 'activeBalance');
            $used = null;
            if ($total !== null && $free !== null) {
                $used = $total - $free;
            }
            $result[$code] = array(
                'free' => $free,
                'used' => $used,
                'total' => $total,
            );
        }
        return $this->safe_balance($result);
    }
    parseOrderStatus (status => Str) => Str {
        $statuses = array(
            'open' => 'open',
            'active' => 'open',
            'done' => 'closed',
            'filled' => 'closed',
            'canceled' => 'canceled',
            'cancelled' => 'canceled',
        );
        return $this->safe_string($statuses, status, status);
    }
    override parseOrder ($order => Dict, $market => MarketInterface | null = null) => Order {
        $id = $this->safe_string($order, 'id');
        $timestamp = $this->safe_timestamp($order, 'createdAt');
        $symbol = $this->safe_string($market, 'symbol');
        return $this->safe_order(array(
            'id' => $id,
            'clientOrderId' => null,
            'info' => $order,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => null,
            'status' => $this->parse_order_status($this->safe_string($order, 'status')),
            'symbol' => $symbol,
            'type' => $this->safe_string($order, 'type'),
            'timeInForce' => null,
            'side' => $this->safe_string_lower($order, 'type'),
            'price' => $this->safe_number($order, 'price'),
            'amount' => $this->safe_number($order, 'amount'),
            'filled' => $this->safe_number($order, 'filledAmount'),
            'remaining' => null,
            'cost' => null,
            'average' => null,
            'trades' => array(),
            'fee' => null,
        ), $market);
    }
    override async createOrder ($symbol => string, type => string, side => string, amount => number, price => number | null = null, params = array()) => Promise<Order> {
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'type' => type,
            'srcCurrency' => $market['baseId'],
            'dstCurrency' => $market['quoteId'],
            'amount' => amount,
            'side' => side,
        );
        if (price !== null) {
            $request['price'] = price;
        }
        $response = $this->request('market/orders/add', 'private', 'POST', $this->extend($request, params));
        $order = $this->safe_dict($response, 'order', $response);
        return $this->parse_order($order, $market);
    }
    override async cancelOrder ($id => string, $symbol => Str = null, params = array()) => Promise<Order> {
        $this->load_markets();
        $request = array(
            'order' => $id,
            'status' => 'canceled',
        );
        $response = $this->request('market/orders/update-status', 'private', 'POST', $this->extend($request, params));
        return $response;
    }
    override async fetchOrder ($id => string, $symbol => Str = null, params = array()) => Promise<Order> {
        $this->load_markets();
        $orders = $this->fetch_orders($symbol, null, null, params);
        for ($i = 0; $i < count($orders); $i++) {
            if ($orders[$i]['id'] === 'strval' ($id)) {
                return $orders[$i];
            }
        }
        throw new OrderNotFound('Order not found => ' . 'strval' ($id));
    }
    override async fetchOrders ($symbol => Str = null, since => Int = null, limit => Int = null, params = array()) => Promise<Orderarray()> {
        $this->load_markets();
        $market = null;
        $request = array();
        if ($symbol !== null) {
            $market = $this->market($symbol);
            $request['srcCurrency'] = $market['baseId'];
            $request['dstCurrency'] = $market['quoteId'];
        }
        $response = $this->request('market/orders/list', 'private', 'POST', $this->extend($request, params));
        $orders = $this->safe_list($response, 'orders', array());
        return $this->parse_orders($orders, $market, since, limit);
    }
    override async fetchOpenOrders ($symbol => Str = null, since => Int = null, limit => Int = null, params = array()) => Promise<Orderarray()> {
        $request = array( 'status' => 'open' );
        return $this->fetch_orders($symbol, since, limit, $this->extend($request, params));
    }
    override async fetchClosedOrders ($symbol => Str = null, since => Int = null, limit => Int = null, params = array()) => Promise<Orderarray()> {
        $request = array( 'status' => 'done' );
        return $this->fetch_orders($symbol, since, limit, $this->extend($request, params));
    }
    override async fetchMyTrades ($symbol => Str = null, since => Int = null, limit => Int = null, params = array()) => Promise<Tradearray()> {
        $request = array( 'status' => 'done' );
        $orders = $this->fetch_orders($symbol, since, limit, $this->extend($request, params));
        return $orders;
    }
}
