<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\wallex as Exchange;

class wallex extends Exchange {
    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'wallex',
            'name' => 'Wallex',
            'countries' => array( 'IR' ),
            'version' => 'v1',
            'rateLimit' => 200,
            'urls' => array(
                'api' => array(
                    'public' => 'https://api.wallex.ir',
                    'private' => 'https://api.wallex.ir',
                ),
                'www' => 'https://wallex.ir',
                'doc' => 'https://docs.wallex.ir',
            ),
            'requiredCredentials' => array(
                'apiKey' => true,
                'secret' => false,
            ),
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'cancelOrder' => true,
                'createOrder' => true,
                'fetchBalance' => true,
                'fetchCurrencies' => false,
                'fetchMarkets' => true,
                'fetchMyTrades' => false,
                'fetchOHLCV' => true,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrders' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
            ),
            'timeframes' => array(
                '1m' => '1',
                '5m' => '5',
                '15m' => '15',
                '30m' => '30',
                '1h' => '60',
                '4h' => '240',
                '1d' => 'D',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'v1/markets',
                        'v1/udf/history',
                    ),
                ),
                'private' => array(
                    'get' => array(
                        'v1/account/balances',
                        'v1/account/openOrders',
                    ),
                    'post' => array(
                        'v1/orders',
                    ),
                    'delete' => array(
                        'v1/orders/{id}',
                    ),
                ),
            ),
        ));
    }

    public function sign(string $path, string $api = 'public', string $method = 'GET', array $params = array(), array $headers = array(), ?string $body = null): mixed {
        $requestPath = $this->implode_params($path, $params);
        $url = $this->urls['api'][$api] . '/' . $requestPath;
        $query = $this->omit($params, $this->extract_params($path));
        if ($api === 'private') {
            $this->check_required_credentials();
            $headers = array(
                'X-API-KEY' => $this->apiKey,
                'Content-Type' => 'application/json',
            );
            if ($query) {
                if ($method === 'GET') {
                    $url .= '?' . $this->urlencode($query);
                } else {
                    $body = $this->json($query);
                }
            }
        } else {
            if ($query) {
                $url .= '?' . $this->urlencode($query);
            }
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function fetch_markets($params = array()): array {
        $response = $this->publicGetV1Markets($params);
        $result = $this->safe_dict($response, 'result', array());
        $symbols = $this->safe_dict($result, 'symbols', array());
        $keys = is_array($symbols) ? array_keys($symbols) : array();
        $markets = array();
        for ($i = 0; $i < count($keys); $i++) {
            $id = $keys[$i];
            $market = $this->safe_dict($symbols, $id, array());
            $baseId = $this->safe_string($market, 'baseAsset');
            $quoteId = $this->safe_string($market, 'quoteAsset');
            if (($baseId === null) || ($quoteId === null)) {
                continue;
            }
            $base = $this->safe_currency_code($baseId);
            $quote = $this->safe_currency_code($quoteId);
            $symbol = $base . '/' . $quote;
            $markets[] = $this->safe_market_structure(array(
                'id' => $id,
                'symbol' => $symbol,
                'base' => $base,
                'quote' => $quote,
                'baseId' => $baseId,
                'quoteId' => $quoteId,
                'active' => true,
                'spot' => true,
                'type' => 'spot',
                'precision' => array(
                    'price' => $this->parse_number($this->parse_precision($this->safe_string($market, 'tickSize', '0'))),
                    'amount' => $this->parse_number($this->parse_precision($this->safe_string($market, 'stepSize', '8'))),
                ),
                'limits' => array(
                    'amount' => array(
                        'min' => $this->safe_number($market, 'minQty'),
                        'max' => null,
                    ),
                    'price' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'cost' => array(
                        'min' => $this->safe_number($market, 'minNotional'),
                        'max' => null,
                    ),
                    'leverage' => array(
                        'min' => null,
                        'max' => null,
                    ),
                ),
                'info' => $market,
            ));
        }
        return $markets;
    }

    public function parse_ticker(array $ticker, ?array $market = null): array {
        $marketSymbol = $market === null ? null : $market['symbol'];
        $stats = $this->safe_dict($ticker, 'stats', array());
        $last = $this->safe_number($stats, 'lastPrice');
        return $this->safe_ticker(array(
            'symbol' => $this->safe_string($ticker, 'symbol', $marketSymbol),
            'timestamp' => null,
            'datetime' => null,
            'high' => $this->safe_number($stats, '24h_highPrice'),
            'low' => $this->safe_number($stats, '24h_lowPrice'),
            'bid' => $this->safe_number($stats, 'bidPrice'),
            'ask' => $this->safe_number($stats, 'askPrice'),
            'open' => null,
            'close' => $last,
            'last' => $last,
            'baseVolume' => $this->safe_number($stats, '24h_volume'),
            'quoteVolume' => $this->safe_number($stats, '24h_quoteVolume'),
            'info' => $ticker,
        ), $market);
    }

    public function fetch_ticker(string $symbol, $params = array()): array {
        $this->load_markets();
        $market = $this->market($symbol);
        $response = $this->publicGetV1Markets($params);
        $result = $this->safe_dict($response, 'result', array());
        $symbols = $this->safe_dict($result, 'symbols', array());
        $ticker = $this->safe_dict($symbols, $market['id']);
        if ($ticker === null) {
            throw new NotSupported($this->id . ' fetchTicker () no $ticker for ' . $symbol);
        }
        return $this->parse_ticker($ticker, $market);
    }

    public function fetch_tickers(?array $symbols = null, $params = array()): array {
        $this->load_markets();
        $response = $this->publicGetV1Markets($params);
        $result = $this->safe_dict($response, 'result', array());
        $symbolsData = $this->safe_dict($result, 'symbols', array());
        $keys = is_array($symbolsData) ? array_keys($symbolsData) : array();
        $rawTickers = array();
        for ($i = 0; $i < count($keys); $i++) {
            $key = $keys[$i];
            $item = $this->safe_dict($symbolsData, $key, array());
            $rawTickers[] = $item;
        }
        return $this->parse_tickers($rawTickers, $symbols);
    }

    public function fetch_balance($params = array()): array {
        $response = $this->privateGetV1AccountBalances($params);
        $data = $this->safe_list($response, 'result', array());
        $balances = array();
        for ($i = 0; $i < count($data); $i++) {
            $balance = $data[$i];
            $currency = $this->safe_string($balance, 'currency');
            if ($currency === null) {
                continue;
            }
            $free = $this->safe_number($balance, 'free', 0);
            $used = $this->safe_number($balance, 'locked', 0);
            $balances[$currency] = array(
                'free' => $free,
                'used' => $used,
                'total' => $this->sum($free, $used),
            );
        }
        return $this->safe_balance($balances);
    }

    public function fetch_ohlcv(string $symbol, string $timeframe = '5m', ?int $since = null, ?int $limit = null, $params = array()): array {
        $this->load_markets();
        $market = $this->market($symbol);
        $resolution = $this->safe_string($this->timeframes, $timeframe, $timeframe);
        $request = array(
            'symbol' => $market['id'],
            'resolution' => $resolution,
        );
        if ($since !== null) {
            $request['from'] = (int) floor($since / 1000);
        }
        if ($limit !== null) {
            $request['countback'] = $limit;
        }
        $response = $this->publicGetV1UdfHistory($this->extend($request, $params));
        $timestamps = $this->safe_list($response, 't', array());
        $opens = $this->safe_list($response, 'o', array());
        $highs = $this->safe_list($response, 'h', array());
        $lows = $this->safe_list($response, 'l', array());
        $closes = $this->safe_list($response, 'c', array());
        $volumes = $this->safe_list($response, 'v', array());
        $result = array();
        for ($i = 0; $i < count($timestamps); $i++) {
            $result[] = array(
                $this->safe_integer($timestamps, $i) * 1000,
                $this->safe_number($opens, $i),
                $this->safe_number($highs, $i),
                $this->safe_number($lows, $i),
                $this->safe_number($closes, $i),
                $this->safe_number($volumes, $i),
            );
        }
        return $result;
    }

    public function create_order(string $symbol, string $type, string $side, float $amount, ?float $price = null, $params = array()): array {
        throw new NotSupported($this->id . ' createOrder () is not supported yet');
    }

    public function cancel_order(string $id, ?string $symbol = null, $params = array()): array {
        throw new NotSupported($this->id . ' cancelOrder () is not supported yet');
    }

    public function fetch_order(string $id, ?string $symbol = null, $params = array()): array {
        throw new NotSupported($this->id . ' fetchOrder () is not supported yet');
    }

    public function fetch_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array()): array {
        throw new NotSupported($this->id . ' fetchOrders () is not supported yet');
    }

    public function fetch_open_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array()): array {
        throw new NotSupported($this->id . ' fetchOpenOrders () is not supported yet');
    }
}
